# Generated by Django 5.2.9 on 2025-12-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sprite_url', models.URLField()),
                ('types', models.JSONField(default=list)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('stats', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pokemons', models.ManyToManyField(related_name='teams', to='pokedex.pokemon')),
            ],
        ),
    ]
